stages:
  - test
  - deploy

before_script:
  - docker info
  - test/clone_samplecode.sh

test-php:
  image: docker:stable
  stage: test
  tags:
    - docker
  services:
    - name: docker:dind
    - name: alpine/git:latest
  script:
    - test/test.sh 5.6
    - test/test.sh 7.0
    - test/test.sh 7.1
    - test/test.sh 7.2
    - test/test.sh 7.3

docker-hub:
  image: docker:stable
  stage: deploy
  tags:
    - docker
  services:
    - name: docker:dind
    - name: alpine/git:latest
  environment:
    name: production
    url: https://hub.docker.com/r/bbdrummer/ubuntu-apache-php
  dependencies:
    - test-php
  script:
    - test/push_image_to_hub.sh
  when: manual
  only:
    refs:
      - master
      - release
