stages:
  - test
  - deploy

before_script:
  - apk add git && apk add curl
  - docker info
  - test/clone_samplecode.sh

.test-setup: &test-setup
  image: docker:stable
  services:
    - name: docker:dind
  stage: test
  tags:
    - docker

php5.6:
  <<: *test-setup
  script:
    - test/test.sh 5.6

php7.0:
  <<: *test-setup
  script:
    - test/test.sh 7.0
  when: manual

php7.1:
  <<: *test-setup
  script:
    - test/test.sh 7.1
  when: manual

php7.2:
  <<: *test-setup
  script:
    - test/test.sh 7.2
  when: manual

php7.3:
  <<: *test-setup
  script:
    - test/test.sh 7.3
  when: manual

docker-hub:
  image: docker:stable
  services:
    - name: docker:dind
  stage: deploy
  tags:
    - docker
  environment:
    name: production
    url: https://hub.docker.com/r/bbdrummer/ubuntu-apache-php
  dependencies:
    - php5.6
    - php7.0
    - php7.1
    - php7.2
    - php7.3
  script:
    - test/push_image_to_hub.sh
  when: manual
  only:
    refs:
      - master
      - release
