stages:
  - test
  - deploy

before_script:
  - apk add git && apk add curl
  - docker info
  - test/clone_samplecode.sh

.test-setup: &test-setup
  image: docker:stable
  services:
    - name: docker:dind
      alias: php-ci-test
  stage: test
  tags:
    - docker-runner

php5.6:
  <<: *test-setup
  when: manual
  script:
    - TEST_PORT=9856 test/test.sh 5.6

php7.0:
  <<: *test-setup
  when: manual
  script:
    - TEST_PORT=9870 test/test.sh 7.0

php7.1:
  <<: *test-setup
  when: manual
  script:
    - TEST_PORT=9871 test/test.sh 7.1

php7.2:
  <<: *test-setup
  script:
    - TEST_PORT=9872 test/test.sh 7.2

php7.3:
  <<: *test-setup
  script:
    - TEST_PORT=9873 test/test.sh 7.3

php7.4:
  <<: *test-setup
  script:
    - TEST_PORT=9874 test/test.sh 7.4

php8.0:
  <<: *test-setup
  script:
    - TEST_PORT=9880 test/test.sh 8.0

docker-hub:
  image: docker:stable
  services:
    - name: docker:dind
  stage: deploy
  tags:
    - docker
  environment:
    name: production
    url: https://hub.docker.com/r/bbdrummer/ubuntu-apache-php
  dependencies:
    - php5.6
    - php7.0
    - php7.1
    - php7.2
    - php7.3
    - php7.4
    - php8.0
  script:
    - test/push_image_to_hub.sh
  when: manual
  only:
    refs:
      - master
      - release
