---
version: 2.1
  
machine:
  services:
    - docker:dind

dependencies:
  pre:
    - docker info
    - test/clone_samplecode.sh

test:
  override:

deployment:
  release:
    branch: master
    commands:
      - test/push_image_to_hub.sh

jobs:
  php5.6:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 5.6
  php7.0:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 7.0
  php7.1:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 7.1
  php7.2:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 7.2
  php7.3:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 7.3
  php7.4:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 7.4
  php8.0:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: test/test.sh 8.0

workflows:
  php-build:
    jobs:
      - php5.6:
          context: docker
      - php7.0:
          context: docker
      - php7.1:
          context: docker
      - php7.2:
          context: docker
      - php7.3:
          context: docker
      - php7.4:
          context: docker
      - php8.0:
          context: docker