---
version: 2.1
  
machine:
  services:
    - docker:dind

dependencies:
  pre:
    - docker info
    - test/clone_samplecode.sh

test:
  override:

deployment:
  release:
    branch: master
    commands:
      - test/push_image_to_hub.sh

jobs:
  php-56:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 5.6
  php-70:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 7.0
  php-71:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 7.1
  php-72:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 7.2
  php-73:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 7.3
  php-74:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 7.4
  php-80:
    docker:
      - image: docker:dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: test/test.sh 8.0

workflows:
  php-build:
    jobs:
      - php-56:
          context: docker
      - php-70:
          context: docker
      - php-71:
          context: docker
      - php-72:
          context: docker
      - php-73:
          context: docker
      - php-74:
          context: docker
      - php-80:
          context: docker