---
version: 2.1
  
machine:
  services:
    - docker

dependencies:
  pre:
    - docker info
    - test/clone_samplecode.sh

test:
  override:
    - test/test.sh 5.6
    - test/test.sh 7.0
    - test/test.sh 7.1
    - test/test.sh 7.2
    - test/test.sh 7.3
    - test/test.sh 7.4
    - test/test.sh 8.0

deployment:
  release:
    branch: master
    commands:
      - test/push_image_to_hub.sh

jobs:
  testing:
    docker:
      - image: docker/dind
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - run: echo "testing..."

workflows:
  php-build:
    jobs:
      - testing:
          context: docker